---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
