---
name: Build Cortex Time Series Storage Plugin
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on:
      group: Default
      labels:
        - self-hosted
        - Linux
        - X64
        - eu-central-de
        - labmonkeys
    steps:
      - uses: actions/checkout@v4
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Compile source with unit and integration tests
        run: |
          make tests
      - name: Persist KAR file
        uses: actions/upload-artifact@v4
        with:
          name: cortex-tss-kar-file
          path: assembly/kar/target/opennms-cortex-tss-plugin.kar
