---
name: Build Cortex Time Series Storage Plugin
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/java-builder:0.1.0.jdk-17.b35
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Compile source without tests
        run: |
          make
      - name: Run system test using Docker Compose
        run: |
          make tests
